    "2crows", "3blackcrows", "3inside", "3linestrike", "3starsinsouth", "3whitesoldiers", "abandonedbaby",
    "advanceblock", "belthold", "breakaway", "closingmarubozu", "concealbabyswall", "counterattack",
    "darkcloudcover", "doji", "dojistar", "dragonflydoji", "engulfing", "eveningdojistar", "eveningstar",
    "gapsidesidewhite", "gravestonedoji", "hammer", "hangingman", "harami", "haramicross", "highwave",
    "hikkake", "hikkakemod", "homingpigeon", "identical3crows", "inneck", "invertedhammer", "kicking",
    "kickingbylength", "ladderbottom", "longleggeddoji", "longline", "marubozu", "matchinglow", "mathold",
    "morningdojistar", "morningstar", "onneck", "piercing", "rickshawman", "risefall3methods", "separatinglines",
    "shootingstar", "shortline", "spinningtop", "stalledpattern", "sticksandwich", "takuri", "tasukigap",
    "thrusting", "tristar", "unique3river", "upsidegap2crows", "xsidegap3methods", nullptr};
