#!/usr/bin/env python3
import argparse
import json
import re
import sys
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs" / "function_reference.md"
OUTPUT = ROOT / "src" / "function_metadata.inc"


@dataclass(frozen=True)
class FunctionMetadata:
    name: str
    category: str
    purpose: str
    example: str


def read(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def cpp_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def normalize_usage(value: str) -> str:
    value = re.sub(r"\s+", " ", value.strip())
    return value.removesuffix(";")


def example_for(category: str, usage: str) -> str:
    usage = normalize_usage(usage)
    if usage.upper().startswith("SELECT "):
        return f"{usage};"
    if category == "Table Functions And Time-Series Builders":
        return f"SELECT * FROM {usage};"
    return f"SELECT {usage};"


def parse_rows() -> list[FunctionMetadata]:
    rows: list[FunctionMetadata] = []
    seen: set[str] = set()
    category = ""
    for line in read(DOCS).splitlines():
        heading = re.fullmatch(r"###\s+(.+)", line)
        if heading:
            category = heading.group(1).strip()
            continue
        if not line.startswith("| `fin_"):
            continue
        parts = [part.strip() for part in line.strip().strip("|").split("|")]
        if len(parts) != 4:
            raise ValueError(f"Could not parse function reference row: {line}")
        name_cell, usage_cell, purpose, _notes = parts
        name_match = re.fullmatch(r"`(fin_[A-Za-z0-9_]+)`", name_cell)
        usage_match = re.fullmatch(r"`(.+)`", usage_cell)
        if not name_match or not usage_match:
            raise ValueError(f"Could not parse function name or usage in row: {line}")
        if not category:
            raise ValueError(f"Function row appears before a category heading: {line}")
        name = name_match.group(1)
        if name in seen:
            raise ValueError(f"Duplicate function metadata row for {name}")
        seen.add(name)
        rows.append(
            FunctionMetadata(
                name=name,
                category=category,
                purpose=purpose,
                example=example_for(category, usage_match.group(1)),
            )
        )
    return rows


def registered_functions() -> set[str]:
    suffixes = {".cpp", ".inc", ".hpp"}
    source = "\n".join(
        read(path)
        for path in sorted((ROOT / "src").rglob("*"))
        if path.suffix in suffixes and path != OUTPUT
    )
    functions = set(re.findall(r'"(fin_[A-Za-z0-9_]+)"', source))
    functions.discard("fin_cdl_")
    return functions


def render(rows: list[FunctionMetadata]) -> str:
    lines = [
        "// Generated by scripts/generate_function_metadata.py from docs/function_reference.md.",
        "// Do not edit by hand.",
        "static const FinanceFunctionMetadata FINANCE_FUNCTION_METADATA[] = {",
    ]
    for row in rows:
        lines.append(
            f"\t{{{cpp_string(row.name)}, {cpp_string(row.category)}, "
            f"{cpp_string(row.purpose)}, {cpp_string(row.example)}}},"
        )
    lines.extend(["\t{nullptr, nullptr, nullptr, nullptr}", "};", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if src/function_metadata.inc is stale")
    args = parser.parse_args()

    rows = parse_rows()
    rendered = render(rows)
    if args.check:
        documented = {row.name for row in rows}
        registered = registered_functions()
        missing = sorted(registered - documented)
        extra = sorted(documented - registered)
        if missing or extra:
            if missing:
                print("Missing metadata rows for registered functions:")
                for name in missing:
                    print(f"  {name}")
            if extra:
                print("Metadata rows for unregistered functions:")
                for name in extra:
                    print(f"  {name}")
            return 1
        try:
            current = read(OUTPUT)
        except FileNotFoundError:
            print(f"{OUTPUT.relative_to(ROOT)} is missing")
            return 1
        if current != rendered:
            print(f"{OUTPUT.relative_to(ROOT)} is stale; run scripts/generate_function_metadata.py")
            return 1
        print(f"Function metadata covers {len(rows)} registered functions.")
        return 0

    OUTPUT.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)} with {len(rows)} function metadata entries.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
